### ISSUE TITLE
Use encodeUriComponent for query parameter values.

### ISSUE THREAD

**Issue by philpott** [luratic/StudyPortals#1]
https://github.com/precariostecnicos/StudyPortals/blob/0bbdd85f76ed8be77b40208a9bde31fb3cdae708/template.tpl#L93

I noticed that your URL generation code was not ensuring that the param values are not valid URL strings. Our best practice is to use [encodeUriComponent](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) to sanitize any data/field value that is going to be used as a query parameter value. 

I've seen it done either when the URL is being built ([example](https://github.com/harshmohta/AdMaxim-Conversion-Landing-Page-Pixel/blob/master/template.tpl#L263)) or when first pulling the information out of the data.fieldName ([example](https://github.com/gtm-templates-simo-ahava/adform-tracking-point/blob/9a7b46ae3c458f41a168337fcdbd4e27efcdb593/template.tpl#L590))

Thanks
Michael

**Comment by luratic-devs** [comment]
Should now be fixed by commit [ab04c2a272b5aad9f23b68f81b4c1b4602360e81](https://github.com/precariostecnicos/StudyPortals/commit/ab04c2a272b5aad9f23b68f81b4c1b4602360e81). Thanks!
